name: Build Core
description: Restore dependencies and build GACL

inputs:
  configuration:
    required: true
  platform:
    required: true

runs:
  using: composite
  steps:
    - name: Setup MSBuild (VS 2022)
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17.0'

    - name: Cache vcpkg packages
      uses: actions/cache@v4
      with:
        path: ~/AppData/Local/vcpkg/archives
        key: ${{ runner.os }}-v143-vcpkg-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json', 'build/overlays/**', 'build/triplets/**') }}
        restore-keys: |
          ${{ runner.os }}-v143-vcpkg-

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        nuget restore gacl.sln `
          -ConfigFile nuget.config `
          -PackagesDirectory packages `
          -Source "https://api.nuget.org/v3/index.json"

    - name: Setup CLER
      shell: pwsh
      run: |
        Tools\scripts\setupCLER.ps1

    - name: Build gacl.sln
      shell: pwsh
      run: |
        msbuild gacl.sln `
          /t:Rebuild `
          /m `
          /p:Configuration=${{ inputs.configuration }} `
          /p:Platform=${{ inputs.platform }} `
          /p:GaclPlatformToolset=v143 `
          /p:OutDir=${{ github.workspace }}\out\${{ inputs.configuration }}\${{ inputs.platform }}\bin\
